In [1]:
from pyg import twod as pyg2d
from pyg import composite as pygc
import numpy as np

In [2]:
plot = pygc.composite()
plot.add_line(np.linspace(0., 2.0 * np.pi),
              np.sin(np.linspace(0., 2.0 * np.pi)))
plot.xlabel(r'x coordinate ($x$) [$\unit{cm}$]')
plot.ylabel(r'y coordinate ($y$) [$\unit{cm}$]')
plot.add_asset("atom.svg", [1.0, 1.0], (4.0, 0.5))
plot.add_asset("atom.svg", [1.0, 1.0], (3.0, -0.5))
plot.add_asset("atom.svg", [1.5, 1.5], (1.0, 0.0))

plot.export('test', force=True)
plot.show('some caption', label=None)

[[ 345.4305586   191.20426527]
 [ 415.51299093  326.39920031]]
set_width: 46.721622 set_height: 46.721617
width: 100.000000 height: 100.000010
scale: 0.467216
fig_width: 625.000000
fig_height: 386.271243
pos: 238.073976, 198.162882
[[ 275.34812627   56.00933023]
 [ 345.4305586   191.20426527]]
set_width: 46.721622 set_height: 46.721617
width: 100.000000 height: 100.000010
scale: 0.467216
fig_width: 625.000000
fig_height: 386.271243
pos: 191.352354, 288.292839
[[ 117.66265354   89.80806399]
 [ 222.78630203  292.60046655]]
set_width: 70.082432 set_height: 70.082425
width: 100.000000 height: 100.000010
scale: 0.700824
fig_width: 625.000000
fig_height: 386.271243
pos: 90.122174, 235.440924
[<svgutils.compose.Panel object at 0x2ad462d69290>, <svgutils.compose.Panel object at 0x2ad462d0a250>, <svgutils.compose.Panel object at 0x2ad462d0a590>, <svgutils.compose.Panel object at 0x2ad462d60950>]
